install(TARGETS ${PROJECT_NAME} RUNTIME DESTINATION bin)
install(FILES ${PROJECT_HEADERS} DESTINATION include/${PROJECT_NAME})

set(CPACK_PACKAGE_NAME "Dark-Wave")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_CONTACT "alex_braun@knu.ua")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "File encryption system with AES-256 encryption")
set(CPACK_PACKAGE_LICENSE "MIT License")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "DarkWave")

set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Oleksii Stepaniuk <alex_braun@knu.ua>")
set(CPACK_DEBIAN_PACKAGE_SECTION "security")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "openssl")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

include(CPack)
